# Estructuras de datos

## Listas

Python tiene varios tipos de datos *compuestos*, utilizados para agrupar otros valores. El más versátil es la lista, la cual puede ser escrita como una lista de valores separados por coma (ítems) entre corchetes. Las listas pueden contener ítems de diferentes tipos

In [1]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

Al igual que las cadenas, las listas se pueden indexar y segmentar:

In [2]:
squares[0]

1

In [3]:
squares[-1]

25

In [4]:
squares[-3:]

[9, 16, 25]

Las listas también admiten operaciones como concatenación:

In [5]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

A diferencia de las cadenas, que son immutable, las listas son de tipo mutable, es decir, es posible cambiar su contenido:

In [6]:
cubes = [1, 8, 27, 46, 125]
cubes[3] = 64
cubes

[1, 8, 27, 64, 125]

También puedes añadir nuevos elementos al final de la lista, utilizando el *método* list.append():

In [7]:
cubes.append(216)
cubes.append(7 ** 3)
cubes

[1, 8, 27, 64, 125, 216, 343]

La asignación simple en Python nunca copia datos. Cuando asignas una lista a una variable, la variable hace referencia a la lista existente. Cualquier cambio que hagas en la lista a través de una variable se verá a través de todas las demás variables que hagan referencia a ella:

In [8]:
rgb = ["Red", "Green", "Blue"]
rgba = rgb
id(rgb) == id(rgba) # hacen referencia al mismo objeto

True

In [9]:
rgba.append("Alph")
rgb

['Red', 'Green', 'Blue', 'Alph']

La función predefinida len() también sirve para las listas:

In [10]:
letters = ['a', 'b', 'c', 'd']
len(letters)

4

Es posible anidar listas (crear listas que contengan otras listas), por ejemplo:

In [11]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [12]:
x[0]

['a', 'b', 'c']

In [13]:
x[0][1]

'b'

## Tuplas

Una tupla está formada por un número de valores separados por comas, por ejemplo:

In [14]:
t = 12345, 54321, 'hello!'
t[0]

12345

In [15]:
t

(12345, 54321, 'hello!')

Las tuplas pueden anidarse:

In [16]:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

Las tuplas son inmutables:

In [17]:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

Pero pueden contener objetos mutables:

In [18]:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

Un problema particular es la construcción de tuplas que contengan 0 o 1 ítem: la sintaxis presenta algunas peculiaridades para estos casos. Las tuplas vacías se construyen mediante un par de paréntesis vacío; una tupla con un ítem se construye poniendo una coma a continuación del valor (no alcanza con encerrar un único valor entre paréntesis). Feo, pero efectivo. Por ejemplo:

In [19]:
empty = ()
len(empty)

0

In [20]:
singleton = 'hello',    # <- observe la coma al final
len(singleton)

1

In [21]:
singleton

('hello',)

La declaración t = 12345, 54321, 'hola!' es un ejemplo de empaquetado de tuplas: los valores 12345, 54321 y 'hola!' se empaquetan juntos en una tupla. La operación inversa también es posible:

In [22]:
x, y, z = t

Esto se llama, apropiadamente, desempaquetado de secuencias, y funciona para cualquier secuencia en el lado derecho del igual. El desempaquetado de secuencias requiere que la cantidad de variables a la izquierda del signo igual sea el tamaño de la secuencia. Nótese que la asignación múltiple es en realidad sólo una combinación de empaquetado de tuplas y desempaquetado de secuencias.

## Conjuntos

Python también incluye un tipo de dato para conjuntos. Un conjunto es una colección no ordenada y sin elementos repetidos. Los usos básicos de éstos incluyen verificación de pertenencia y eliminación de entradas duplicadas. Los conjuntos también soportan operaciones matemáticas como la unión, intersección, diferencia, y diferencia simétrica.

Las llaves o la función `set()` pueden usarse para crear conjuntos. Notá que para crear un conjunto vacío tienes que usar `set()`, no `{}`; esto último crea un diccionario vacío.

Una pequeña demostración:

In [23]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)

{'orange', 'pear', 'banana', 'apple'}


In [24]:
'orange' in basket

True

In [25]:
'crabgrass' in basket

False

In [26]:
a = set('abracadabra')
b = set('alacazam')
a                     

{'a', 'b', 'c', 'd', 'r'}

In [27]:
a - b # diferencia

{'b', 'd', 'r'}

In [28]:
a | b # union

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [29]:
a & b # intersección

{'a', 'c'}

In [30]:
a ^ b # diferencia simétrica

{'b', 'd', 'l', 'm', 'r', 'z'}

## Diccionarios

Es mejor pensar en un diccionario como un conjunto de pares *clave:valor* con el requerimiento de que las claves sean únicas (dentro de un diccionario). Un par de llaves crean un diccionario vacío: `{}`.

Un pequeño ejemplo de uso de un diccionario:

In [31]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [32]:
tel['jack']

4098

In [33]:
tel['irv'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127, 'irv': 4127}

In [34]:
list(tel)

['jack', 'sape', 'guido', 'irv']

In [35]:
sorted(tel)

['guido', 'irv', 'jack', 'sape']

In [36]:
'guido' in tel

True

In [37]:
'jack' not in tel

False